### ISSUE TITLE
defaults are not shown with graftM -h

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#10]
This just makes things a little less confusing for the user.

**Comment by geronimp** [comment]
Will be in next commit

**Comment by wwood** [comment]
github has this neat thing where if you include "fix #10" in the commit
message of the commit it'll automatically close the issue, and link the
commit in the issue page so you can see which commit did the fixing.

On 17 March 2015 at 21:50, geronimp <notifications@github.com> wrote:

> Will be in next commit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geronimp/graftM/issues/10#issuecomment-82738652>.
>



-- 
--
Ben Woodcroft
http://ecogenomic.org/users/ben-woodcroft <http://www.ecogenomic.org/>
