### ISSUE TITLE
graftM create builds an HMM from sequences that have not been deduplicated

### ISSUE THREAD

**Issue by caity-s** [geronimp/graftM#121]
Hello Ben,

GraftM create builds the HMM using the sequences provided, and seems to be resulting in an HMM biased to duplicates.

Thanks,
Caitlin

**Comment by wwood** [comment]
and also the HMM is created using sequences that ultimately do not pass the length cutoff

**Comment by geronimp** [comment]
and also the HMM is not dereplicated at the genus level, which would be a nice feature. I'm working on create now so leave this one to me.

**Comment by wwood** [comment]
and also the duplicates are included in the diamond db, so it is possible to map to a read that is in the diamond database, but is not in the tree.

**Comment by wwood** [comment]
One might argue that diamond sequences shouldn't be deduplicated, because the deduplication happens only for those positions aligned to the HMM, and diamond doesn't care about HMMs. What do you think @geronimp ?

**Comment by geronimp** [comment]
@wwood Yes I dont think we should de-duplicate the diamond sequences. The branch I'm working on now includes sequences that have not been deduplicated, but it ""doesn't"" remove those which did not pass the min percent align filter. 

imo i think this is the best way.

**Comment by wwood** [comment]
this issue seems to be fixed now thanks to Joel
