### ISSUE TITLE
--output_stats should be renamed, and it should work

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#15]
Easy enough to change the argparse setup, but it seems to not actually use the directory as output

**Comment by geronimp** [comment]
Updated. Had to modify the output of graftM to make this work, but its good in the long run. Now you don't have to specify if you want basic statistics, they are simply given as default. But graftM will now give you one file, even if you run multiple samples at once. Within this file you'll be given each of the runs, and the basic statistics file. 

Thanks again,
Joel
