### ISSUE TITLE
should handle proteins as input

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#16]
A possibly sizeable feature request - it would be useful to be able to pipe proteins in. Some outputs would need to be removed e.g. the output file of nucleotide sequences.

**Comment by geronimp** [comment]
I'm thinking of just making this a flag, do you agree?

**Comment by wwood** [comment]
That's a first step. But I think a mature solution should auto-detect
whether it is protein or nucleotide, because its the kind of thing people
forget to specify.

On 17 March 2015 at 22:08, geronimp <notifications@github.com> wrote:

> I'm thinking of just making this a flag, do you agree?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geronimp/graftM/issues/16#issuecomment-82742994>.
>



-- 
--
Ben Woodcroft
http://ecogenomic.org/users/ben-woodcroft <http://www.ecogenomic.org/>

**Comment by geronimp** [comment]
Latest commit can now handle protein sequence as input. When the input sequence type is not specified, it will attempt to guess. On the odd chance that the guess is incorrect, you can manually tell graftM the sequence type with the  --input_sequence_type flag, with either 'nucleotide', or 'protein' as inputs. If GraftM fails to auto-predict sequence please let me know and I'll see what I can do about it.

As with the other pipelines, protein sequences can be submitted to graftM in either fasta, or fastq format. 

Thanks,
Joel
