### ISSUE TITLE
missing output files?

### ISSUE THREAD

**Issue by xvazquezc** [geronimp/graftM#184]
Hi again,
I got to complete my test run with the dataset from one of my replicate samples but based on the description of the outputs from the `graft` option in the [wiki](https://github.com/geronimp/graftM/wiki/Using-GraftM-and-its-options), the following files are missing:

- command_log.txt
- my_reads_coverage_table.txt
- my_reads_relative_table.txt
- my_reads_placements.guppy

Any idea why? The job got completed in the cluster with no error message:

> 02/12/2016 04:23:03 PM INFO: Working on 028-LFA_S1_R1
> 02/12/2016 04:23:03 PM INFO: Working on forward reads
> 02/12/2016 04:41:15 PM INFO: Found 573 read(s) that may be eukaryotic
> 02/12/2016 04:42:11 PM INFO: 10659 read(s) detected
> 02/12/2016 04:42:11 PM INFO: aligning reads to reference package database
> 02/12/2016 04:45:07 PM INFO: Filtered 1788 short sequences from the alignment
> 02/12/2016 04:45:07 PM INFO: 8871 sequences remaining
> 02/12/2016 04:45:07 PM INFO: Working on reverse reads
> 02/12/2016 05:03:18 PM INFO: Found 576 read(s) that may be eukaryotic
> 02/12/2016 05:04:13 PM INFO: 10606 read(s) detected
> 02/12/2016 05:04:13 PM INFO: aligning reads to reference package database
> 02/12/2016 05:07:04 PM INFO: Filtered 1782 short sequences from the alignment
> 02/12/2016 05:07:04 PM INFO: 8824 sequences remaining
> 02/12/2016 05:07:05 PM INFO: Placing reads into phylogenetic tree
> 02/13/2016 09:10:38 AM INFO: Placements finished
> 02/13/2016 09:10:44 AM INFO: Reading classifications
> 02/13/2016 09:10:45 AM INFO: Reads classified
> 02/13/2016 09:10:50 AM INFO: 6463 reads found that crossover in 028-LFA_S1_R1_forward_clustered.fa
> 02/13/2016 09:12:02 AM INFO: Writing summary table
> 02/13/2016 09:12:02 AM INFO: Writing biom file
> 02/13/2016 09:12:02 AM INFO: Building summary krona plot
> 02/13/2016 09:12:03 AM INFO: Cleaning up
> 02/13/2016 09:12:03 AM INFO: Done, thanks for using graftM!
> 
>                          
>                              GraftM 0.9.4
> 
>                                 GRAFT
> 
>                        Joel Boyd, Ben Woodcroft
> 
>                                                          __/__
>                                                   ______|
>           _- - _                         ________|      |_____/
>            - -            -             |        |____/_
>            - _     >>>>  -   >>>>   ____|
>           - _-  -         -             |      ______
>              - _                        |_____|
>            -                                  |______
>             
> 

Job resources allocated:
```
#PBS -l nodes=12:ppn=1
#PBS -l vmem=450gb
#PBS -l walltime=100:00:00
```
Job command:
```
graftM graft --forward high_quality_genomes/028-LFA_S1_R1.fastq --reverse high_quality_genomes/028-LFA_S1_R2.fastq --force \
--graftm_package ~/bin/mypythondir/mypythonenv/mypythonenv/share/4.05.2013_08_greengenes_97_otus.gpkg \
--output_directory graftm --threads 12 --input_sequence_type nucleotide --euk_check
```
Job completion message
> Exec host:  kc05b11/2+kc05b11/1+kc05b11/0+kc05b12/12+kc05b14/12+kc05b16/4+kc05b16/0+kc09b16/0+kc08b03/3+kc08b03/2+kc08b04/2+kc08b04/1
> Execution terminated
> Exit_status=0
> resources_used.cput=47:39:10
> resources_used.mem=429466580kb
> resources_used.vmem=429998872kb
> resources_used.walltime=16:49:14

**Comment by geronimp** [comment]
Hello Xabier,

That would be because I've neglected to update the wiki page with some recent updates we've made to GraftM - I apologise for this! 

I'll work on updating that as soon as possible, thank you for flagging this for me

I notice also that you are running GraftM with the same directory being passed to the `--output_directory` flag as the previous issue you raised (https://github.com/geronimp/graftM/issues/182). I'll note that run creates a new output directory, and if the `--force` flag is used, the previous run is overwritten. Please be careful that if you plan to do multiple runs of graftM runs in the same directory, make sure to give the output directories for each a unique name.

If you have any more bug reports, please keep posting them.

Joel

**Comment by geronimp** [comment]
Updates have been posted.
