### ISSUE TITLE
taxa missing in Krona

### ISSUE THREAD

**Issue by xvazquezc** [geronimp/graftM#185]
Hi,

I was taking a look on the Krona files and I found at least one taxa (c__Thermoplasmata) that appears in the combined_count_table.txt but it's missing from the krona.html output when opened. However, it is in the code of the html file. It happens in all my 12 samples.
I attach one complete output in case you want to take a look.

Xabier

[080-LFC_S12.zip](https://github.com/geronimp/graftM/files/183266/080-LFC_S12.zip)

**Comment by xvazquezc** [comment]
Default collapse option on. My bad

**Comment by geronimp** [comment]
Oops haha
