### ISSUE TITLE
mafft-linsi or similar as default for create alignment

### ISSUE THREAD

**Issue by geronimp** [geronimp/graftM#218]
Accurate phylogenetic placement relies on good alignment of both the reference sequences used to build the tree, and the query sequences to be inserted. We can help on the reference tree side of things by making the default alignment algorithm more robust (by using mafft-linsi). Obviously for larger alignments this wont be feasible. But its something to look into to improve reference alignments when we have, say, <500 sequences?

Joel

**Comment by wwood** [comment]
mafft by itself chooses the best algorithm based on the number of input sequences, IIRC. Are the default choices not aligning with what we want?
