### ISSUE TITLE
Error with graft command

### ISSUE THREAD

**Issue by StephanieannCarr** [geronimp/graftM#244]
Hi - I'm trying to get graft M up and running and I'm getting an error during the tree step. Any ideas? Thanks! 

$ graftM graft --forward G3001R1.fastq --reverse
 G3001R2.fastq --graftm_package ../4.40.2013_08_greengenes_97_otus.with_euks.gpkg --out
put_directory G3001graftM

01/22/2018 06:52:25 PM INFO: Working on G3001R1
01/22/2018 06:52:25 PM INFO: Working on forward reads
01/22/2018 07:00:47 PM INFO: 8758 read(s) detected
01/22/2018 07:00:47 PM INFO: aligning reads to reference package database
01/22/2018 07:03:45 PM INFO: Filtered 1061 short sequences from the alignment
01/22/2018 07:03:45 PM INFO: 7697 sequences remaining
01/22/2018 07:03:45 PM INFO: Working on reverse reads
01/22/2018 07:13:20 PM INFO: 8598 read(s) detected
01/22/2018 07:13:20 PM INFO: aligning reads to reference package database
01/22/2018 07:16:26 PM INFO: Filtered 1027 short sequences from the alignment
01/22/2018 07:16:26 PM INFO: 7571 sequences remaining
01/22/2018 07:16:26 PM INFO: Merging pair G3001R1_forward_hits.aln.fa, G3001R1_reverse_
hits.aln.fa
01/22/2018 07:16:27 PM INFO: Placing reads into phylogenetic tree
Traceback (most recent call last):
  File "/home/shaghaghis/.local/bin/graftM", line 444, in <module>
    Run(args).main()
  File "/home/shaghaghis/.local/lib/python2.7/site-packages/graftm/run.py", line 588, i
n main
    self.graft()
  File "/home/shaghaghis/.local/lib/python2.7/site-packages/graftm/run.py", line 492, i
n graft
    clusterer)
  File "/home/shaghaghis/.local/lib/python2.7/site-packages/graftm/timeit.py", line 10,
 in timed
    result = method(*args, **kw)
  File "/home/shaghaghis/.local/lib/python2.7/site-packages/graftm/pplacer.py", line 18
1, in place
    jplace = self.pplacer(files.jplace_output_path(), args.output_directory, files.comb
_aln_fa(), args.threads)
  File "/home/shaghaghis/.local/lib/python2.7/site-packages/graftm/pplacer.py", line 28
, in pplacer
    extern.run(cmd)
  File "/home/shaghaghis/.local/lib/python2.7/site-packages/extern/__init__.py", line 4
6, in run
    stdout)
extern.ExternCalledProcessError: Command pplacer -j 5 --verbosity 0 --out-dir G3001graf
tM -c ../4.40.2013_08_greengenes_97_otus.with_euks.gpkg/97_otus_with_euks.gpkg.refpkg G
3001graftM/combined_alignment.aln.fa returned non-zero exit status -9.
STDERR was: STDOUT was:

**Comment by wwood** [comment]
Hi, apologies for the slow response here. There's nothing I can see that might be causing the problem. Can I ask what version of GraftM / pplacer is being used? Also, would you be able to send the contents of the output directory, perhaps via email as detailed at http://ecogenomic.org/personnel/dr-ben-woodcroft so we can have a look?
Thanks, ben

**Comment by StephanieannCarr** [comment]
Hi Ben! 

Sorry, I should have returned to that note, we figured it out!! It was a memory issue - we just didn't have enough. We initiated a larger cloud instance and had no problem. There was a similar issue on the SupportM page, which helped us determine our issue. 

What a fun and great tool!

**Comment by wwood** [comment]
Ah right, glad to you managed to fix it. Thanks for the encouraging comments.
