### ISSUE TITLE
Missing options on docs for "graft"

### ISSUE THREAD

**Issue by kyclark** [geronimp/graftM#246]
I notice the Wiki for "graft" (https://github.com/geronimp/graftM/wiki/Using-GraftM-and-its-options) lists options for "graft" which differ from the the output of "graftm graft --help." Calling these "readme" and "man," respectively:
```
$ diff readme man
3c3
< --bootstrap_contigs
---
> --decoy_database
6a7
> --expand_search_contigs
14c15
< --merge_reads
---
> --max_samples_for_krona
16c17
< --no_clustering
---
> --no_merge_reads
25a27
> --search_method
29d30
< --version
```

**Comment by wwood** [comment]
hi, thanks for noticing. I've updated the graft docs so they are now in date.
