### ISSUE TITLE
LookupError: unknown encoding: utf8

### ISSUE THREAD

**Issue by s4351982** [geronimp/graftM#252]
I got an error at the last step when I ran one of my samples using graftM, while the other samples were fine. Can anyone advise me about the issue? Thanks

05/17/2018 04:10:32 PM INFO: Working on SB8205_S33_R1_001
05/17/2018 04:10:32 PM INFO: Working on forward reads
05/17/2018 04:20:05 PM INFO: 37320 read(s) detected
05/17/2018 04:20:06 PM INFO: aligning reads to reference package database
05/17/2018 04:23:45 PM INFO: Filtered 10568 short sequences from the alignment
05/17/2018 04:23:45 PM INFO: 26752 sequences remaining
05/17/2018 04:23:49 PM INFO: Working on reverse reads
05/17/2018 04:33:23 PM INFO: 37203 read(s) detected
05/17/2018 04:33:23 PM INFO: aligning reads to reference package database
05/17/2018 04:36:56 PM INFO: Filtered 10525 short sequences from the alignment
05/17/2018 04:36:56 PM INFO: 26678 sequences remaining
05/17/2018 04:36:58 PM INFO: Placing reads into phylogenetic tree
05/18/2018 11:12:17 AM INFO: Placements finished
05/18/2018 11:12:28 AM INFO: Reading classifications
05/18/2018 11:12:30 AM INFO: Reads classified
05/18/2018 11:13:06 AM INFO: 18647 reads found that crossover in SB8205_S33_R1_001_forward_clustered.fa
05/18/2018 11:20:50 AM INFO: Writing summary table
05/18/2018 11:20:50 AM INFO: Writing biom file
Traceback (most recent call last):
  File "/usr/local/bin/graftM", line 345, in <module>
    Run(args).main()
  File "/usr/local/lib/python2.7/dist-packages/graftm/run.py", line 526, in main
    self.graft()
  File "/usr/local/lib/python2.7/dist-packages/graftm/run.py", line 445, in graft
    hit_read_count_list)
  File "/usr/local/lib/python2.7/dist-packages/graftm/run.py", line 123, in summarise
    biom_successful = self.s.write_biom(base_list, placements_list, f)
  File "/usr/local/lib/python2.7/dist-packages/graftm/summarise.py", line 138, in write_biom
    table.to_hdf5(biom_file_io, 'GraftM graft')
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 3605, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 3557, in axis_dump
    data=[i.encode('utf8') for i in ids],
LookupError: unknown encoding: utf8

**Comment by wwood** [comment]
Hi,
I've not seen this error before, but searching on the internet suggests there might be something amiss with your Python installation, and that potentially re-installation may help? This doesn't seem to be an issue related to graftm, specifically.

**Comment by wwood** [comment]
Alrighty, good to hear. I'm closing this issue for now, but feel free to reopen it if there is anything further.
Thanks, ben
