### ISSUE TITLE
graftM create error while creating package

### ISSUE THREAD

**Issue by ckeuschn** [geronimp/graftM#262]
Hi

I try to create my own package with graftM create but get the following error:

graftM create --sequences pmoa7809.fasta --taxonomy pmoa4qiime_7890.tax --alignment pmoa7809.aln --rerooted_tree f
asttree_rerooted.tree

                             GraftM 0.11.1
05/15/2019 09:59:57 AM WARNING: Program found with multiple commands: taxit FastTreeMP hmmalign mafft. Arbitrarily selecting fasttree

                            CREATE

                   Joel Boyd, Ben Woodcroft

                                                    /
              >a                                   /
              -------------                       /
              >b                        |        |
              --------          >>>     |  GPKG  |
              >c                        |________|
              ----------

05/15/2019 09:59:57 AM INFO: Building gpkg for pmoa7809.gpkg
05/15/2019 09:59:57 AM INFO: Building seqinfo and taxonomy file from input taxonomy
05/15/2019 09:59:57 AM INFO: Checking for duplicate sequences
05/15/2019 09:59:57 AM INFO: Building HMM from alignment
05/15/2019 10:00:04 AM INFO: Filtered 0 short sequences from the alignment
05/15/2019 10:00:04 AM INFO: 7809 sequences remaining
05/15/2019 10:00:04 AM INFO: Checking for incorrect or fragmented reads
05/15/2019 10:00:41 AM INFO: Building HMM from alignment
05/15/2019 10:00:47 AM INFO: Filtered 0 short sequences from the alignment
05/15/2019 10:00:47 AM INFO: 7809 sequences remaining
05/15/2019 10:00:48 AM INFO: Deduplicating sequences
05/15/2019 10:00:48 AM INFO: Removed 872 sequences as duplicates, leaving 6937 non-identical sequences
05/15/2019 10:00:56 AM INFO: Generating log file
05/15/2019 10:01:51 AM INFO: Building seqinfo and taxonomy file from input taxonomy
 FM986164.1 '__environmental_samples' with multiple parents __RA14_methanotroph_group and __Methylocystis
 KF757043.1 '__Proteobacteria' with multiple parents Bacteria(MOB_like) and Bacteria(AOB_like)
 KF757043.1 '__environmental_samples' with multiple parents __RA14_methanotroph_group and __Betaproteobacteria
 HQ906571.1 '__TUSC-like' with multiple parents __Methylococcaceae and __candidate_division_NC10
 HQ906571.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __NC10(pxmA)
 FJ529769.1 '__environmental_samples' with multiple parents __RA14_methanotroph_group and Bacteria(MOB_like)
 GQ857575.1 '__typeIIb' with multiple parents __environmental_samples and __Alphaproteobacteria
 EF623814.1 '__environmental_samples' with multiple parents __RA14_methanotroph_group and __Alphaproteobacteria
 AJ299968.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __Betaproteobacteria
 AJ299968.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede2
 GQ219583.1 '__RA21-like' with multiple parents __RA21_group and __Alphaproteobacteria
 KF757085.1 '__typeIIa' with multiple parents __Methylocystaceae and __Methylocystis
 KF757085.1 '__environmental_samples' with multiple parents __RA14_methanotroph_group and __typeIIae1
 JF780906.1 '__typeIa' with multiple parents __Methylococcaceae and __Gammaproteobacteria
 JF780906.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __typeIae1
 JN426904.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __Alphaproteobacteria
 JN426904.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede5
 JQ040554.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __uncultured_methanotrophic_bacterium
 JQ040554.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede7
 GQ219582.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __RA21-likee1
 AM749116.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __Methylococcales
 AF037108.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __Nitrosomonadales
 FJ529734.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __environmental_samplese3
 FJ529734.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede12
 FJ529734.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede13
 AF148524.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __Proteobacteriae1
 AF148524.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede15
 AF148524.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede16
 HQ883360.1 '__typeIb' with multiple parents __Methylococcaceae and __Methylococcus
 HQ883360.1 '__RPCs' with multiple parents __typeIb and __typeIbe1
 JQ040565.1 '__environmental_samples' with multiple parents __RA14_methanotroph_group and __Proteobacteria
 JQ040565.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __uncultured_methanotrophic_proteobacterium
 EU275115.1 '__RPCs' with multiple parents __typeIb and __MethylococcaceaetypeIb
 KM210551.1 '__Methylacidiphilaceae' with multiple parents __Methylacidiphilales and __unclassified_Verrucomicrobia
 KF031192.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __Gammaproteobacteria
 JF706214.2 '__unclassified' with multiple parents __M84-P105(pxmA) and __NC10
 JF706214.2 '__unclassified' with multiple parents __M84-P105(pxmA) and __unclassifiede20
 AB669172.1 '__environmental_samples' with multiple parents __RA14_methanotroph_group and __Methylocystaceae
 AB669172.1 '__typeIIb' with multiple parents __environmental_samples and __environmental_samplese7
 AB669172.1 '__pmoA-2' with multiple parents __typeIIbe1 and __typeIIbe2
 HQ883355.1 '__typeIa' with multiple parents __Methylococcaceae and __Methylobacter
 HQ883355.1 '__deep-sea-1' with multiple parents __typeIa and __typeIae2
 JX262153.1 '__TUSC-like' with multiple parents __Methylococcaceae and __Candidatus_Methylomirabilis
 JX262153.1 '__NC10(pxmA)' with multiple parents __TUSC-likee1 and __TUSC-likee2
 EU223855.1 '__Verr3)' with multiple parents __Methylacidiphilum_fumariolicum(pxmA and __Methylacidiphilum_infernorum_V4(pxmA
 JF780909.1 '__unclassified' with multiple parents __M84-P105(pxmA) and __typeI
05/15/2019 10:01:52 AM INFO: Creating reference package
Traceback (most recent call last):
  File "/Users/christoph.keuschnig/miniconda2/bin/graftM", line 409, in <module>
    Run(args).main()
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/graftm/run.py", line 657, in main
    threads = self.args.threads
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/graftm/create.py", line 811, in main
    no_reroot)
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/graftm/create.py", line 227, in _taxit_create
    extern.run(cmd)
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/extern/__init__.py", line 46, in run
    stdout)
extern.ExternCalledProcessError: Command taxit create -f /var/folders/sg/8n6k9cc51d9936m50jcn2ksh0000gn/T/tmp2N0csN/pmoa7809_deduplicated_aligned.fasta -P pmoa7809.gpkg.refpkg -t /var/folders/sg/8n6k9cc51d9936m50jcn2ksh0000gn/T/graftmxx0iiw.tree -s /var/folders/sg/8n6k9cc51d9936m50jcn2ksh0000gn/T/graftmdWYm36.tree_log -c -l  /var/folders/sg/8n6k9cc51d9936m50jcn2ksh0000gn/T/tmp2N0csN/pmoa7809 -T /var/folders/sg/8n6k9cc51d9936m50jcn2ksh0000gn/T/tmp2N0csN/pmoa7809_taxonomy.csv -i /var/folders/sg/8n6k9cc51d9936m50jcn2ksh0000gn/T/tmp2N0csN/pmoa7809_seqinfo.csv --no-reroot returned non-zero exit status 1.
STDERR was: Traceback (most recent call last):
  File "/Users/christoph.keuschnig/miniconda2/bin/taxit", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/christoph.keuschnig/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psycopg2-binary>=2.7.3.1' distribution was not found and is required by taxtastic
STDOUT was:

I do have the psycopg2 package installed. Any ideas?
Thanks for your help!

**Comment by wwood** [comment]
Hi,

It appears to be failing on the last step, where the package is tested by running `graftM graft` with the new gpkg. It is possible that when `graftM create` invokes `graftM graft` like this it does not setup the PYTHONPATH etc correctly.

Does the package get created? If so, maybe try using it. If it works, then you can ignore the error.
Hope that helps.
ben

**Comment by ckeuschn** [comment]
Thanks for the answer, it actually did not create a package. I had installed that version by conda so i removed it and installed it by pip again. Now everything runs - great program!!

**Comment by wwood** [comment]
Thanks for getting back to us, and for the kind words.
