### ISSUE TITLE
evalues for search appear to be ignored

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#31]
in Hmmer, hmmsearch and nhmmer methods do not appear to ever read the eval argument, presumably meaning the default evalue is used even when an evalue is specified when graftM is called on the command line.

**Comment by geronimp** [comment]
I'm not sure what you mean. This seems fine to me:

nhmmer:
```
graftM graft --eval 1e-07 --forward two_examples2.windowed.fa --graftm_package /srv/db/graftm/0/61_otus.gpkg/ 

command_log.txt:
cat two_examples2.windowed.fa | tee  | nhmmer -E 1e-07 --cpu 5 --tblout GraftM_output/two_examples2/two_examples2.hmmout.csv /srv/db/graftm/0/61_otus.gpkg/61_otus.hmm - >/dev/null
```

and hmmsearch:
```
s4293811@keating:~/testing_files/testing_graftM/03_mcrA$ graftM graft --eval 1e-07 --forward eg.1.fa --graftm_package /srv/db/graftm/0/mcrA_gpkg/ --force                                                                                                                           

command log:
orfm eg.1.fa  | hmmsearch -E 1e-07 --cpu 5 --domtblout GraftM_output/eg/eg.hmmout.csv /srv/db/graftm/0/mcrA_gpkg/mcrA.hmm - >/dev/null

```

**Comment by wwood** [comment]
Ah sorry, I misinterpreted the liclipse warning. I thought it was saying that the eval argument was unused, when actually it was complaining that `eval` is a reserved keyword (like `print`), so shouldn't be used as a variable name.

But, having said that there may (or may not) be a subtle bug. In `Hmmer.extract_orfs` the evalue is no used, so maybe the orfs of interest may not be extracted in some strange circumstances e.g. with specified evalues lower than the hmmsearch default, if such a thing is even possible.

Anyway, I think potentially a better way of structuring this code might be to have a Hmmer class that provides command lines just as strings, and then a separate part of the code uses those strings e.g. 
```
class Hmmsearch
   def init(self, cpus=None, evalue=None)
      self._cpus = cpus
      self._evalue = evalue

   def hmmsearch_command_line(self, hmm_path, input_path=None, domtblout=None)
       if input_path==None: input_path='-' #default to stdin
       if domtblout==None: domtblout='-' #default to stdout
       
       return 'hmmsearch -E %s --cpu %s --domtblout %s %s - >/dev/null " % (self._evalue, self._cpus, output_path, hmm)
```
That saves you from repeatedly specifying all the parameters for hmmer runs, you just keep a single hmmsearch object which the pipeline uses repeatedly. I note also that cpus is not used in extract_orfs.

Same could be used for other programs. This isn't the highest priority thing, but if you try it make sure you merge my `orfm_params` branch first.
