### ISSUE TITLE
use faster nhmmer

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#42]
As of hmmer3.1b2 nhmmer can be much faster if you follow the directions at http://cryptogenomicon.org/2015/04/15/hmmer-3-1-beta-test-2-released/

To do
* Update the code use this by default, including in graftm create
* Remake the nucleotide packages with makehmmerdb
* This needs testing in terms of the numbers of reads detected, as well.

**Comment by geronimp** [comment]
Does this pass all unit tests?

**Comment by wwood** [comment]
Hmm, this is an issue, not a pull request (sorry). Patches needed.

**Comment by wwood** [comment]
We decided not to implement this because it requires a database to be made out the query sequences, which doesn't really suit our workflow.
