### ISSUE TITLE
More details on making refpkg using graftM create

### ISSUE THREAD

**Issue by fauziharoon** [geronimp/graftM#47]
I am still not sure on how to make a refpkg. Is there an example of the taxonomy file? 
--taxonomy TAX        File containing two tab separated columns, the first
                        with the ID of the sequences, the second with the
                        taxonomy string (GreenGenes taxonomy file format).
What kind of tree? Is it only from fasttree output? Can I use other tree making programs to make the tree?

Thanks for looking into this.

**Comment by wwood** [comment]
It sort of depends on what kind of gene you have - is this one that largely follows the species tree? It will be harder if the answer is no.

You don't need a tree as input, all you need is the taxonomy file and a multiple sequence alignment.

A taxonomy file is in approximately the following format
```
gene_number3     k__KingdomName; p__PhylumName; c__Class, o__Order; f__Family; g__Genus; s__
etc.
```
Make sense? Let us know how you go.

**Comment by fauziharoon** [comment]
It is within the same class but different clades. I am trying to see if the
genes are abundant in which clades (eg. 1-10 clades). Can i have that
information in the taxonomy file?

**Comment by wwood** [comment]
Yeh you can just make the taxonomy say whatever you would like to make 
it most informative for you.

**Comment by wwood** [comment]
Taxonomy format now documented in `graftM create -h`, and can also input annotated tree rather than taxonomy file
