### ISSUE TITLE
Doesn't deal well with large numbers of input files

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#70]
By going through each file one by one when many input files are provided, the bottleneck is orfm. If instead multiple orfm instances were run simultaneously, we could squeeze a bit more performance out. Maybe not the easiest thing to implement.

.. or, maybe could just make orfm faster, though I think that requires multi-threading it which is  not especially trivial.

**Comment by geronimp** [comment]
OrfM is less of a problem now, and this issue is not exactly specific.. Shall we close?

**Comment by wwood** [comment]
indeed, I thought wrong, happily.
